FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /gateway-worker ./cmd/gateway-worker

FROM gcr.io/distroless/base-debian12
COPY --from=builder /gateway-worker /gateway-worker
ENTRYPOINT ["/gateway-worker"]
