version: "3.9"

services:
  temporal:
    image: temporalio/auto-setup:1.22.3
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgres
#      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    ports:
      - "8233:7233"
    depends_on:
      - temporal-postgres
    networks:
      - tmprl_net

  temporal-postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    volumes:
      - temporal-db:/var/lib/postgresql/data
    networks:
      - tmprl_net

  temporal-ui:
    image: temporalio/ui:latest
    environment:
      - TEMPORAL_ADDRESS=itap-cloud.com:8233       # адреса gRPC фронтенда Temporal
      - TEMPORAL_UI_PORT=8080                 # внутрішній порт UI-сервера
      - TEMPORAL_DEFAULT_NAMESPACE=default    # опціонально
      # приклади ще корисних змінних:
      # - TEMPORAL_UI_PUBLIC_PATH=/           # якщо треба сервити з підшляху
      # - TEMPORAL_DISABLE_WRITE_ACTIONS=false
    ports:
      - "8088:8080"                           # відкриваємо UI на http://localhost:8088
    depends_on:
      - temporal
    networks:
      - tmprl_net

  gateway-api:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=default
    ports:
      - "8080:8080"
    depends_on:
      - temporal
    networks:
      - tmprl_net

  gateway-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=default
    depends_on:
      - temporal
    networks:
      - tmprl_net

  python-worker:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - TEMPORAL_ADDRESS=itap-cloud.com:8233
      - TEMPORAL_NAMESPACE=default
      - MAX_CONCURRENT_ACTIVITIES=1
    depends_on:
      - temporal
    networks:
      - tmprl_net

volumes:
  temporal-db:

networks:
  tmprl_net:
