FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
ARG BIN_PATH=./cmd/gateway-worker
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/worker ${BIN_PATH}

FROM gcr.io/distroless/base-debian12
COPY --from=builder /out/worker /worker
ENTRYPOINT ["/worker"]
